[colors]
foregrount = "#d2c8c0"
background = "#192a39"
cursor_bg  = "#d2c8c0"
cursor_border = "#d2c8c0"
cursor_fg = "#192a39"
selection_bg = "#d2c8c0"
selection_fg = "#192a39"

ansi = [
	"#192a39",
	"#c04e99",
	"#af644d",
	"#b67033",
	"#577d91",
	"#647b92",
	"#367cba",
	"#d2c8c0",
]

brights = [
	"#88898a",
	"#c04e99",
	"#af644d",
	"#b67033",
	"#577d91",
	"#647b92",
	"#367cba",
	"#e0d8d2",
]